# Basic Options
# 基础配置
[options]

[options.basic]
comment="基础配置"

[[options.basic.options]]
comment="The directory to store the downloaded file"
commentZH="下载文件的存放文件夹"
full="--dir"
simple="-d"
example="--dir=path"

[[options.basic.options]]
comment='''
Downloads the URIs listed in FILE.
You can specify multiple sources for a single entity by putting multiple URIs on a single line separated by the TAB character.
Additionally, options can be specified after each URI line.
Option lines must start with one or more white space characters (SPACE or TAB) and must only contain one option per line.
Input files can use gzip compression.
See also the --deferred-input option.
See also the --save-session option.
'''
commentZH='''
下载FILE中列出的URI。
你可以为一个实体指定多个来源，把多个URI放在一行中，用TAB字符隔开。
此外，可以在每行URI后面指定选项。选项行必须以一个或多个空白字符（SPACE或TAB）开始，每行只能包含一个选项。
输入文件可以使用gzip压缩。也请参见--deferred-input选项。另见 --save-session 选项。
'''
full="--input-file"
simple="-i"
example="--input-file=needDownload.txt"

[[options.basic.options]]
comment='''
The file name of the log file. If - is specified, log is written to stdout. If empty string("") is specified, or this option is omitted, no log is written to disk at all.
'''
commentZH='''
日志文件的文件名。如果指定了 -，则将日志写入标准输出。如果指定了空字符串("")，或者省略了此选项，则根本不会将日志写入磁盘。
'''
full="--log"
simple="-l"
example="--log=aria2.log"

[[options.basic.options]]
comment='''
Set the maximum number of parallel downloads for every queue item. See also the --split option. Default: 5
'''
commentZH='''
设置每个队列项目的最大并行下载次数。另见--split选项。默认值：5
'''
full="--max-concurrent-downloads"
simple="-j"
example="--max-concurrent-downloads=10"

[[options.basic.options]]
comment='''
Check file integrity by validating piece hashes or a hash of entire file.
This option has effect only in BitTorrent, Metalink downloads with checksums or HTTP(S)/FTP downloads with --checksum option.
If piece hashes are provided, this option can detect damaged portions of a file and re-download them.
If a hash of entire file is provided, hash check is only done when file has been already download. This is determined by file length.
If hash check fails, file is re-downloaded from scratch. If both piece hashes and a hash of entire file are provided, only piece hashes are used.
Default: false
'''
commentZH='''
通过验证片段哈希值或整个文件的哈希值来检查文件的完整性。
这个选项只对BitTorrent、带校验的Metalink下载或带--校验选项的HTTP(S)/FTP下载有效。
如果提供了片断的哈希值，这个选项可以检测到文件的损坏部分，并重新下载它们。
如果提供了整个文件的哈希值，哈希值检查只在文件已经被下载时进行。这是由文件长度决定的。
如果哈希值检查失败，文件将从头下载。如果同时提供片状散列和整个文件的散列，则只使用片状散列。
默认值：false
'''
full="--check-integrity"
simple="-V"
example="-V false"

[[options.basic.options]]
comment='''
Continue downloading a partially downloaded file.
Use this option to resume a download started by a web browser or another program which downloads files sequentially from the beginning.
Currently this option is only applicable to HTTP(S)/FTP downloads.
'''
commentZH='''
继续下载一个部分下载的文件。
使用这个选项来恢复由网络浏览器或其他程序开始的下载，这些程序从一开始就按顺序下载文件。
目前这个选项只适用于HTTP(S)/FTP下载。
'''
full="--continue"
simple="-c"
example="--continue false"

[[options.basic.options]]
comment='''
The help messages are classified with tags.
A tag starts with #. For example, type --help=#http to get the usage for the options tagged with #http.
If non-tag word is given, print the usage for the options whose name includes that word.
Available Values: #basic, #advanced, #http, #https, #ftp, #metalink, #bittorrent, #cookie, #hook, #file, #rpc, #checksum, #experimental, #deprecated, #help, #all
Default: #basic
'''
commentZH='''
帮助消息使用标签进行分类。标签以#开头。
例如，键入 --help=#http 以获取带有 #http 标记的选项的用法。
如果给出了非标签词，则打印名称中包含该词的选项的用法。
可用值：#basic、#advanced、#http、#https、#ftp、#metalink、#bittorrent、#cookie、#hook、#file、#rpc、#checksum、#experimental、#deprecated、#help、#all
默认值：#basic
'''
full="--help"
simple="-h"
example="--help=#http"

[options.normal]
comment="HTTP/FTP/SFTP选项

[[options.normal.options]]
comment='''
Use a proxy server for all protocols.
To override a previously defined proxy, use "".
You also can override this setting and specify a proxy server for a particular protocol using --http-proxy, --https-proxy and --ftp-proxy options. This affects all downloads.
The format of PROXY is [http://][USER:PASSWORD@]HOST[:PORT].
See also ENVIRONMENT section.
'''
commentZH='''
继续下载一个部分下载的文件。
使用这个选项来恢复由网络浏览器或其他程序开始的下载，这些程序从一开始就按顺序下载文件。
目前这个选项只适用于HTTP(S)/FTP下载。
'''
full="--all-proxy"
simple=""
example="--all-proxy=http://aaa:bbbb@exmple.com:80"



